"""empty message

Revision ID: f610bf799e52
Revises: 
Create Date: 2021-11-03 13:18:46.531200

"""
from alembic import op
import sqlalchemy as sa
import random
import string


# revision identifiers, used by Alembic.
revision = 'f610bf799e52'
down_revision = None
branch_labels = None
depends_on = None

def get_random_string(length = 16):
    characters = string.ascii_letters + string.digits + string.punctuation
    characters = characters.replace('"', '').replace("'", "").replace('`', '')
    return ''.join(random.choice(characters) for i in range(length))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    example_table = op.create_table('Examples',
    sa.Column('IdExample', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(255), nullable=False),
    sa.PrimaryKeyConstraint('IdExample')
    )
    op.bulk_insert(example_table, [
        {"Description": get_random_string(random.randint(8, 20))} for i in range(200)
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Examples')
    # ### end Alembic commands ###
