version: '3'

services:
  {{ cookiecutter.project_name }}:
    image: {{ cookiecutter.project_name }}
    container_name: {{ cookiecutter.project_name }}
    env_file: '.env'
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes: 
      - '.:/code'

