[isyflask.project.definition]
name = "{{ cookiecutter.project_name }}"
description = ""

[isyflask.template.files]
model = "templates/isyflask/model.txt"
service = "templates/isyflask/service.txt"
controller = "templates/isyflask/controller.txt"
endpoint = "templates/isyflask/routes.txt"

[isyflask.project.folders]
root = "api"
models = "api/app/Data/Models"
services = "api/app/Services"
controllers = "api/app/Controllers"
endpoints = "api/routes/"