version: '3'

services:
  flask-pattern:
    image: flask-pattern
    container_name: flask-pattern
    env_file: '.env'
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes: 
      - '.:/code'

