"""empty message

Revision ID: f610bf799e52
Revises: 
Create Date: 2021-11-03 13:18:46.531200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f610bf799e52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dumps',
    sa.Column('IdDump', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IdDump')
    )
    op.create_table('Examples',
    sa.Column('IdExample', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('IdExample')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Examples')
    op.drop_table('Dumps')
    # ### end Alembic commands ###
